### ISSUE TITLE
Update windows compilers

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pycppad-feedstock#19]
Hey all

This feedstock is directly specifying `vs2017_win-64` as a dependency,
https://github.com/conda-forge/pycppad-feedstock/blob/6ddd983364a0a2b7c2bb066529c83177722f63c6/recipe/meta.yaml#L16-L20

but should just rely on the `{{ compiler('c') }}` function to provide the correct compilers on windows. In particular, conda-forge has moved on to vs2019 as the default compiler a while ago already, and doesn't support 32-bit builds anymore.

If you think you need vs2017, please let us know why (generally vs2019 and vs2022 should be fully compatible). If it's really necessary, please use the dedicated mechanism in `conda_build_config.yaml` for that, i.e.
```
c_compiler:     # [win]
  - vs2017      # [win]
cxx_compiler:   # [win]
  - vs2017      # [win]
```
as opposed to specifying it in `meta.yaml` directly.

**Comment by jcarpent** [comment]
@jorisv Could you handle it too?
